"""HTML report renderer — turns repo-map.json into a browsable report.

Usage from CLI:
    code-mapper /path --lint --html              # writes repo-map-report.html
    code-mapper /path --lint --html out.html
"""
import html
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><title>Code Mapper Report — {project}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, sans-serif; margin: 0; padding: 0;
         background: #1e1e1e; color: #e0e0e0; }}
  header {{ background: #252526; padding: 16px 24px; border-bottom: 1px solid #444; }}
  h1 {{ margin: 0; font-size: 22px; color: #4ec9b0; }}
  .meta {{ color: #888; font-size: 13px; margin-top: 4px; }}
  .summary {{ display: flex; gap: 24px; padding: 16px 24px; background: #2a2a2a;
              border-bottom: 1px solid #444; flex-wrap: wrap; }}
  .stat {{ display: flex; flex-direction: column; min-width: 80px; }}
  .stat .n {{ font-size: 28px; font-weight: 600; color: #4ec9b0; }}
  .stat.high .n {{ color: #f48771; }}
  .stat.med .n {{ color: #dcdcaa; }}
  .stat.low .n {{ color: #9cdcfe; }}
  .stat .label {{ font-size: 11px; color: #888; text-transform: uppercase; }}
  .controls {{ padding: 12px 24px; background: #252526; border-bottom: 1px solid #444; }}
  .controls input, .controls select {{ background: #1e1e1e; color: #e0e0e0;
              border: 1px solid #555; padding: 6px 10px; border-radius: 3px;
              font-family: inherit; font-size: 13px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; padding: 10px 16px; background: #2d2d30; color: #4ec9b0;
        font-size: 12px; text-transform: uppercase; cursor: pointer;
        user-select: none; border-bottom: 1px solid #444; }}
  th:hover {{ background: #3a3a3d; }}
  td {{ padding: 8px 16px; border-bottom: 1px solid #2a2a2a; font-size: 13px;
        font-family: Consolas, Menlo, monospace; }}
  tr:hover td {{ background: #2a2a2a; }}
  .sev {{ display: inline-block; padding: 2px 8px; border-radius: 3px;
          font-size: 11px; font-weight: 600; text-transform: uppercase; }}
  .sev.high {{ background: #5a1d1d; color: #f48771; }}
  .sev.med  {{ background: #3a3a1d; color: #dcdcaa; }}
  .sev.low  {{ background: #1d2d3a; color: #9cdcfe; }}
  .rule {{ color: #c586c0; }}
  .file {{ color: #ce9178; }}
  .desc {{ color: #d4d4d4; }}
  footer {{ padding: 12px 24px; color: #666; font-size: 11px; text-align: center; }}
</style>
</head><body>
<header>
  <h1>Code Mapper Report</h1>
  <div class="meta">{project} · {n_files} files · {n_findings} findings</div>
</header>
<div class="summary">
  <div class="stat high"><span class="n">{n_high}</span><span class="label">High</span></div>
  <div class="stat med"><span class="n">{n_med}</span><span class="label">Med</span></div>
  <div class="stat low"><span class="n">{n_low}</span><span class="label">Low</span></div>
  <div class="stat"><span class="n">{n_files}</span><span class="label">Files</span></div>
  <div class="stat"><span class="n">{n_funcs}</span><span class="label">Funcs</span></div>
  <div class="stat"><span class="n">{n_classes}</span><span class="label">Classes</span></div>
</div>
<div class="controls">
  <input id="filter" type="text" placeholder="Filter findings (file, rule, desc)..."
         oninput="filterTable()" style="width: 320px;">
  <select id="sevFilter" onchange="filterTable()">
    <option value="">All severities</option>
    <option value="high">High only</option>
    <option value="med">Med + High</option>
    <option value="low">Low only</option>
  </select>
</div>
<table id="findings"><thead>
<tr><th onclick="sortBy(0)">Sev</th><th onclick="sortBy(1)">File</th>
    <th onclick="sortBy(2)">Line</th><th onclick="sortBy(3)">Rule</th>
    <th onclick="sortBy(4)">Description</th></tr>
</thead><tbody>
{rows}
</tbody></table>
<footer>Generated by Code Mapper · {generated}</footer>
<script>
let sortDir = {{}};
function sortBy(col) {{
  const tbody = document.querySelector('#findings tbody');
  const rows = Array.from(tbody.querySelectorAll('tr'));
  sortDir[col] = !sortDir[col];
  const dir = sortDir[col] ? 1 : -1;
  rows.sort((a, b) => {{
    const av = a.cells[col].innerText.toLowerCase();
    const bv = b.cells[col].innerText.toLowerCase();
    if (col === 2) return (parseInt(av)||0 - parseInt(bv)||0) * dir;
    return av.localeCompare(bv) * dir;
  }});
  rows.forEach(r => tbody.appendChild(r));
}}
function filterTable() {{
  const q = document.getElementById('filter').value.toLowerCase();
  const sev = document.getElementById('sevFilter').value;
  const sevAllowed = {{
    '': ['high','med','low'], 'high': ['high'],
    'med': ['high','med'], 'low': ['low']
  }}[sev];
  document.querySelectorAll('#findings tbody tr').forEach(r => {{
    const txt = r.innerText.toLowerCase();
    const rsev = r.dataset.sev;
    const matchQ = !q || txt.includes(q);
    const matchS = sevAllowed.includes(rsev);
    r.style.display = (matchQ && matchS) ? '' : 'none';
  }});
}}
</script>
</body></html>"""


def _collect_findings(repo_map_dict: dict) -> list[dict]:
    out: list[dict] = []
    stats = repo_map_dict.get("stats", {})
    for key in ("lint_findings", "ai_findings", "verified_findings",
                "claude_findings", "pattern_findings"):
        out.extend(stats.get(key, []))
    xref = stats.get("xref")
    if xref and isinstance(xref, dict):
        out.extend(xref.get("findings", []))
    return out


def _render_diff_section(diff: dict | None) -> str:
    if not diff:
        return ""
    n_new = diff.get("n_new", 0)
    n_resolved = diff.get("n_resolved", 0)
    n_unchanged = diff.get("n_unchanged", 0)
    if n_new == 0 and n_resolved == 0:
        return ('<div class="diff-section">'
                '<h2>vs Baseline</h2>'
                '<p style="color:#888">No changes since baseline.</p></div>')
    new_rows = "".join(
        f'<li>[{html.escape((f.get("severity") or "?").lower())}] '
        f'<span class="file">{html.escape(f.get("file_path") or f.get("file") or "?")}</span>:'
        f'{f.get("line") or 0} '
        f'<span class="rule">{html.escape(f.get("rule") or "?")}</span>'
        f'</li>'
        for f in (diff.get("new") or [])[:30]
    )
    resolved_rows = "".join(
        f'<li><span class="file">{html.escape(f.get("file_path") or f.get("file") or "?")}</span>:'
        f'{f.get("line") or 0} '
        f'<span class="rule">{html.escape(f.get("rule") or "?")}</span></li>'
        for f in (diff.get("resolved") or [])[:30]
    )
    return f'''<div class="diff-section" style="padding:16px 24px; background:#2a2a2a; border-bottom:1px solid #444;">
  <h2 style="margin:0 0 12px 0; font-size:18px; color:#4ec9b0;">vs Baseline</h2>
  <div style="display:flex; gap:24px; flex-wrap:wrap;">
    <div class="stat high"><span class="n">{n_new}</span><span class="label">New</span></div>
    <div class="stat" style="color:#73c990;"><span class="n">{n_resolved}</span><span class="label">Resolved</span></div>
    <div class="stat"><span class="n">{n_unchanged}</span><span class="label">Unchanged</span></div>
  </div>
  {f'<h3 style="margin:16px 0 6px 0; color:#f48771; font-size:14px;">NEW:</h3><ul style="margin:0; padding-left:20px;">{new_rows}</ul>' if new_rows else ''}
  {f'<h3 style="margin:16px 0 6px 0; color:#73c990; font-size:14px;">RESOLVED:</h3><ul style="margin:0; padding-left:20px;">{resolved_rows}</ul>' if resolved_rows else ''}
</div>'''


def render_html(repo_map_dict: dict, project_path: str = "", diff: dict | None = None) -> str:
    findings = _collect_findings(repo_map_dict)
    rank = {"high": 3, "med": 2, "low": 1}
    findings.sort(
        key=lambda f: (
            -rank.get((f.get("severity") or "low").lower(), 0),
            f.get("file_path") or f.get("file") or "",
            f.get("line") or 0,
        )
    )
    sev_counts = {"high": 0, "med": 0, "low": 0}
    for f in findings:
        sev = (f.get("severity") or "low").lower()
        if sev in sev_counts:
            sev_counts[sev] += 1

    rows = []
    for f in findings:
        sev = (f.get("severity") or "low").lower()
        file_p = f.get("file_path") or f.get("file") or "?"
        line = f.get("line") or 0
        rule = f.get("rule") or f.get("type") or "?"
        desc = (f.get("desc") or f.get("message") or "")[:300]
        rows.append(
            f'<tr data-sev="{html.escape(sev)}">'
            f'<td><span class="sev {html.escape(sev)}">{html.escape(sev)}</span></td>'
            f'<td class="file">{html.escape(file_p)}</td>'
            f'<td>{line}</td>'
            f'<td class="rule">{html.escape(rule)}</td>'
            f'<td class="desc">{html.escape(desc)}</td>'
            f'</tr>'
        )

    nodes = repo_map_dict.get("nodes", [])
    n_files = sum(1 for n in nodes if n.get("type") == "file")
    n_funcs = sum(1 for n in nodes if n.get("type") == "function")
    n_classes = sum(1 for n in nodes if n.get("type") == "class")

    from datetime import datetime as _dt
    rendered = HTML_TEMPLATE.format(
        project=html.escape(project_path or "(unknown)"),
        n_files=n_files, n_funcs=n_funcs, n_classes=n_classes,
        n_findings=len(findings), n_high=sev_counts["high"],
        n_med=sev_counts["med"], n_low=sev_counts["low"],
        rows="\n".join(rows) if rows else
            '<tr><td colspan="5" style="text-align:center;color:#888">No findings</td></tr>',
        generated=_dt.now().isoformat(timespec="seconds"),
    )
    diff_html = _render_diff_section(diff)
    if diff_html:
        # Inject the diff section just below the summary
        rendered = rendered.replace(
            "<div class=\"controls\">",
            diff_html + "<div class=\"controls\">",
            1,
        )
    return rendered


def write_html_report(repo_map, output_path: Path, project_path: str = "",
                      diff: dict | None = None) -> Path:
    if hasattr(repo_map, "to_dict"):
        d = repo_map.to_dict()
    elif hasattr(repo_map, "stats"):
        d = {"stats": repo_map.stats, "nodes": []}
    else:
        d = repo_map
    output_path.write_text(render_html(d, project_path, diff=diff), encoding="utf-8")
    return output_path
